site_name: virtualguard's Note
site_url: https://note.virtualguard101.xyz
repo_url: https://github.com/virtualguard101/note
repo_name: virtualguard101/note
edit_uri: blob/main/docs/

theme:
  name: material
  language: zh
  custom_dir: overrides
  # favicon: https://note.virtualguard101.xyz/assets/logo.png
  favicon: https://note.virtualguard101.com/assets/logo1.jpg

  font:
    text: "'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"
    code: "'Cascadia Mono', 'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"

  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil
    # tag:
      # default: fontawesome/solid/hashtag

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    # - content.code.annotate
    # - content.action.edit
    - content.tabs.link

    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    # - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.indexes
    # - navigation.tracking
    # - navigation.footer
    - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/javascripts/mathjax.js
        # - assets/javascripts/comments.js
        # - assets/javascripts/links.js
      css_files:
        - assets/webfonts/Cascadia Mono/font.css
        - assets/webfonts/LXGW WenKai Screen/font.css
        - assets/stylesheets/theme.css
        - assets/stylesheets/feature.css
        - assets/stylesheets/temp-patch.css

  # - redirects:
  #     redirect_maps:

hooks:
  - scripts/copyright.py
  - scripts/links.py
  - scripts/rss.py
  - scripts/fancybox.py
  # - scripts/notes_links_dev.py

extra:
  analytics:
    provider: google
    property: G-3JKT1BJEB6
    # property: G-Q0XX9SKFVP

extra_css:
  - assets/webfonts/Cascadia Mono/font.css
  - assets/webfonts/LXGW WenKai Screen/font.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/feature.css
  - assets/stylesheets/temp-patch.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  # - callouts
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      # auto_title: true
      # linenums: true
      # anchor_linenums: true
      # line_spans: __span # When this option is set, each line of a code block is wrapped in a span, which is essential for features like line highlighting to work correctly
      use_pygments: true

      # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options
      extend_pygments_lang:
        - name: antlr4
          lang: antlr
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - toc:
      # https://python-markdown.github.io/extensions/toc/
      permalink: true
      separator: "-"
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - overrides

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  links:
    anchors: warn
    unrecognized_links: warn
    